server:
  port: 9801
elasticsearch:
  host: 192.168.1.2
  port: 9200
spring:
  application:
    name: search-data-sync-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.2:3306/shop_goods?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root