server:
  port: 9301
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.2:3306/shop_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.2:8848

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.ashin.pojo

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:10086/eureka
